import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import Marquee from "./Components/MarqueeData/MarqueeData";
import MarqueeData from "./Components/MarqueeData/MarqueeData";

export const metadata = {
  title: "Skillsphere | Learn Anything",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">      
        {children}
        </body>
    </html>
  );
}
